FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg   && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY api/ /app/api/
COPY worker/ /app/worker/
COPY worker/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

CMD ["python", "-m", "worker.worker"]
